---
- hosts: deploy
  connection: local
  become: yes

- name: Download cfssl
  get_url:
    url: https://pkg.cfssl.orgi/R1.2/cfssl_linux-amd64 
    dest: /usr/local/bin/cfssl
    mode: '0755'

- name: Download cfssl-json
  get_url:  
    url:  https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
    mode: '0755'


- name: create directories for keys if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0775'
  with_items:
    - "{{ playbook_dir }}/admin"
    - "{{ playbook_dir }}/api"
    - "{{ playbook_dir }}/ca"
    - "{{ playbook_dir }}/clients"
    - "{{ playbook_dir }}/controller"
    - "{{ playbook_dir }}/proxy"
    - "{{ playbook_dir }}/scheduler"
    - "{{ playbook_dir }}/service-account"
  


